displayMap :- game_state(main_game),
write('#################################################################################################'), nl,
write('#         North America         #        Europe         #                 Asia                  #'), nl,
write('#                               #                       #                                       #'), nl,
write('#       [NA1('), info_wilayah(na1,_,Jna1), write(Jna1),
write(')'),
write(']-[NA2('), info_wilayah(na2,_,Jna2), write(Jna2),
write(')'),
write(']       #                       #                                       #'), nl,
write('-----------|       |----[NA5('), info_wilayah(na5,_,Jna5), write(Jna5),
write(')'),
write(']----[E1('), info_wilayah(e1,_,Je1), write(Je1),
write(')'),
write(']-[E2('), info_wilayah(e2,_,Je2), write(Je2),
write(')'),
write(']----------[A1('), info_wilayah(a1,_,Ja1), write(Ja1),
write(')'),
write('] [A2('), info_wilayah(a2,_,Ja2), write(Ja2),
write(')'),
write('] [A3('), info_wilayah(a3,_,Ja3), write(Ja3),
write(')'),
write(']-----------'), nl, 
write('#       [NA3('), info_wilayah(na3,_,Jna3), write(Jna3),
write(')'),
write(']-[NA4('), info_wilayah(na4,_,Jna4), write(Jna4),
write(')'),
write(']       #       |       |       #        |       |       |              #'), nl,
write('#          |                    #    [E3('), info_wilayah(e3,_,Je3), write(Je3),
write(')'),
write(']-[E4('), info_wilayah(e4,_,Je4), write(Je4),
write(')'),
write(']    ####     |       |       |              #'), nl,
write('###########|#####################       |       |-[E5('), info_wilayah(e5,_,Je5), write(Je5),
write(')'),
write(']-----[A4('), info_wilayah(a4,_,Ja4), write(Ja4),
write(')'),
write(']----+----[A5('), info_wilayah(a5,_,Ja5), write(Ja5),
write(')'),
write(']           #'), nl,
write('#          |                    ########|#######|###########             |                      #'), nl,
write('#       [SA1('), info_wilayah(sa1,_,Jsa1), write(Jsa1),
write(')'),
write(']                #       |       |          #             |                      #'), nl,
write('#          |                    #       |    [AF2('), info_wilayah(af2,_,Jaf2), write(Jaf2),
write(')'),
write(']      #          [A6('), info_wilayah(a6,_,Ja6), write(Ja6),
write(')'),
write(']---[A7('), info_wilayah(a7,_,Ja7), write(Ja7),
write(')'),
write(']         #'), nl,
write('#   |---[SA2('), info_wilayah(sa2,_,Jsa2), write(Jsa2),
write(')'),
write(']---------------------[AF1('), info_wilayah(af1,_,Jaf1), write(Jaf1),
write(')'),
write(']---|          #             |                      #'), nl,
write('#   |                           #               |          ##############|#######################'), nl,
write('#   |                           #            [AF3('), info_wilayah(af3,_,Jaf3), write(Jaf3),
write(')'),
write(']      #             |                      #'), nl,
write('----|                           #                          #          [AU1('), info_wilayah(au1,_,Jau1), write(Jau1),
write(')'),
write(']---[AU2('), info_wilayah(au2,_,Jau2), write(Jau2),
write(')'),
write(']-------'), nl,
write('#                               #                          #                                    #'), nl,
write('#       South America           #         Africa           #          Australia                 #'), nl,
write('#################################################################################################'), nl, !.